load("//cuttlefish/bazel:rules.bzl", "cf_cc_library")

package(
    default_visibility = ["//:android_cuttlefish"],
)

cf_cc_library(
    name = "insecure_json_storage",
    srcs = ["insecure_json_storage.cpp"],
    hdrs = ["insecure_json_storage.h"],
    deps = [
        "//cuttlefish/common/libs/utils:base64",
        "//cuttlefish/common/libs/utils:files",
        "//cuttlefish/common/libs/utils:json",
        "//cuttlefish/host/commands/secure_env/storage",
        "//cuttlefish/result",
        "//libbase",
        "@jsoncpp",
    ],
)

cf_cc_library(
    name = "storage",
    srcs = ["storage.cpp"],
    hdrs = ["storage.h"],
    deps = [
        "//cuttlefish/result",
        "@keymaster//:libkeymaster_messages",
    ],
)

cf_cc_library(
    name = "tpm_storage",
    srcs = ["tpm_storage.cpp"],
    hdrs = ["tpm_storage.h"],
    deps = [
        ":storage",
        "//cuttlefish/host/commands/secure_env:tpm_crypto",
        "//cuttlefish/host/commands/secure_env:tpm_resource_manager",
        "//cuttlefish/result",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@jsoncpp",
        "@tpm2-tss//:tpm2-tss2-esys",
        "@tpm2-tss//:tpm2-tss2-util",
        "@tpm2-tss//:tpm2-tss2-rc",
    ],
)
