git_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "ms-tpm-20-ref",
    build_file = "@//build_external/ms-tpm-20-ref:BUILD.ms-tpm-20-ref.bazel",
    commit = "b9b2fe1eb1af5307e66e3e3e47653b461efc3561",  # android16-qpr2-release
    patches = [
        "@//build_external/ms-tpm-20-ref:0001-Add-riscv64-to-RADIX_BITS-detection.patch",
    ],
    patch_args = ["-p1"],
    remote = "https://android.googlesource.com/platform/external/ms-tpm-20-ref",
)
